/** Sample documents offered in the "Try a sample" gallery. Files live in
 *  apps/web/public/samples and are generated by `npm run samples`. */
export interface SampleDoc {
  /** Public path, also used as the downloaded File name's source. */
  file: string;
  fileName: string;
  name: string;
  description: string;
  /** Short tag shown on the card. */
  meta: string;
  kind: "valid" | "error";
}

export const SAMPLE_DOCS: SampleDoc[] = [
  {
    file: "/samples/signed-letter.pdf",
    fileName: "signed-letter.pdf",
    name: "Signed letter",
    description:
      "A one-page business letter with a letterhead, a hand-signed close, and a footer — all three regions are found.",
    meta: "1 page · all regions",
    kind: "valid",
  },
  {
    file: "/samples/service-agreement.pdf",
    fileName: "service-agreement.pdf",
    name: "Service agreement",
    description:
      "A three-page contract with the signature on the final page. Exercises multi-page handling.",
    meta: "3 pages",
    kind: "valid",
  },
  {
    file: "/samples/project-memo.pdf",
    fileName: "project-memo.pdf",
    name: "Internal memo",
    description:
      "Letterhead only — no signature or footer. Shows how missing regions are reported.",
    meta: "1 page · missing regions",
    kind: "valid",
  },
  {
    file: "/samples/letter-photo.png",
    fileName: "letter-photo.png",
    name: "Letter image",
    description:
      "A letter as a PNG — processed as a single page (no text layer, so AI is recommended).",
    meta: "image",
    kind: "valid",
  },
  {
    file: "/samples/letter.docx",
    fileName: "letter.docx",
    name: "Word document",
    description:
      "A .docx letter, rendered to a page image in the browser before extraction.",
    meta: "docx",
    kind: "valid",
  },
  {
    file: "/samples/corrupt.pdf",
    fileName: "corrupt.pdf",
    name: "Damaged file",
    description:
      "Looks like a PDF but the body is malformed. Triggers a graceful, readable error.",
    meta: "expected to fail",
    kind: "error",
  },
  {
    file: "/samples/not-a-pdf.pdf",
    fileName: "not-a-pdf.pdf",
    name: "Disguised text file",
    description:
      "A plain text file renamed “.pdf”. Rejected by inspecting the magic bytes, not the extension.",
    meta: "expected to fail",
    kind: "error",
  },
];
